name: "Cached Poetry action"
description: "A GitHub action that caches Poetry and your project's dependencies."

inputs:
  additional-dependency-groups:
    description: >
      Additional dependency groups to install (like using `poetry install --with ...`).
      Write these as a JSON list.
  poetry-home:
    description: Where to install Poetry
    default: poetry
  poetry-cache-dir:
    description: Where to install Poetry packages
    default: poetry_cache
  poetry-version:
    description: Version of Poetry to install
    required: true
  python-version:
    description: Python version to install
    required: true

outputs:
  was-poetry-cached:
    description: "Whether Poetry was loaded from a cache"
    value: ${{ steps.poetry-cache.outputs.cache-hit }}
  were-poetry-packages-cached:
    description: "Whether Poetry packages were loaded from a cache"
    value: ${{ steps.poetry-packages-cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Set Poetry env vars
      shell: bash
      run: |
        echo "POETRY_HOME=$(pwd)/${{ inputs.poetry-home }}" >> $GITHUB_ENV
        echo "POETRY_CACHE_DIR=$(pwd)/${{ inputs.poetry-cache-dir }}" >> $GITHUB_ENV

    - name: Add Poetry to path
      shell: bash
      run: echo "$POETRY_HOME/bin" >> $GITHUB_PATH

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Cache Poetry
      id: poetry-cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.poetry-home }}
        key: poetry-cache-${{ runner.os }}-python${{ inputs.python-version }}-poetry${{ inputs.poetry-version }}

    - name: Cache Poetry packages
      id: poetry-packages-cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.poetry-cache-dir }}
        key: |
          poetry-packages-cache-${{ runner.os }}-python${{ inputs.python-version }}-poetry${{ inputs.poetry-version }}-${{ hashFiles('**/pyproject.toml') }}

    - name: Install Poetry if not cached
      if: ${{ steps.poetry-cache.outputs.cache-hit != 'true' }}
      shell: bash
      env:
        POETRY_VERSION: ${{ inputs.poetry-version }}
      run: |
        python3 -m venv $POETRY_HOME
        $POETRY_HOME/bin/pip install poetry==$POETRY_VERSION

    - name: Generate additional Poetry args
      id: poetry-extra-args
      if: ${{ steps.poetry-packages-cache.outputs.cache-hit != 'true' }}
      shell: python
      env:
        additional_dependency_groups: ${{ inputs.additional-dependency-groups }}
      run: |
        import json
        import os
        import re

        dep_groups = json.loads(os.getenv("additional_dependency_groups"))

        # Sanitize! We don't want arbitrary code exec
        if not all(re.match(r"^\w+$", i) for i in dep_groups):
          raise ValueError("Invalid dependency group name(s)")
        with_args = " ".join(f"--with {i}" for i in dep_groups)

        # Write to Github output
        with open(os.environ["GITHUB_OUTPUT"], "at") as f:
          f.write(f"extra_args={with_args}")

    - name: Install dependencies if not cached
      if: ${{ steps.poetry-packages-cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: poetry install --no-root ${{ steps.poetry-extra-args.outputs.extra_args }}
